const express = require("express");
require("dotenv").config();

const app = express();
const port = 3000;

app.use(express.json());

async function testGemini() {
  try {
    const response = await fetch(
      "https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent?key=" +
        process.env.GEMINI_API_KEY,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [
            {
              parts: [{ text: "Hello Gemini" }],
            },
          ],
        }),
      }
    );

    const data = await response.json();

    console.log("FULL GEMINI RESPONSE:", JSON.stringify(data, null, 2));

    // ✅ SAFE ACCESS
    if (data.candidates && data.candidates.length > 0) {
      console.log(
        "Gemini Text:",
        data.candidates[0].content.parts[0].text
      );
    } else {
      console.error("Gemini returned no candidates.");
    }
  } catch (err) {
    console.error("Gemini Fetch Error:", err.message);
  }
}

testGemini();

app.listen(port, () => {
  console.log(`Server running on http://localhost:${port}`);
});









//const express = require('express');
//const bodyParser = require('body-parser');
//const { GoogleGenerativeAI } = require('@google/generative-ai');
//const pdf = require('html-pdf'); // Or 'puppeteer' for more robust conversion
//const fs = require('fs');
//require('dotenv').config();
//
//const app = express();
//const port = 3000;
//app.use(express.json());
//
//app.use(bodyParser.json());
//app.use(express.static('public')); // Serve static files like CSS for HTML resume template
//
//const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
//const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
//const geminiModel = genAI.getGenerativeModel({
//  model: "gemini-1.5-flash-latest"
//});






 // Use gemini-1.5-flash for faster, cheaper if available
//
//
//
//// Route to generate resume HTML
//app.post('/generate-resume-html', async (req, res) => {
//    const { skills, projects, education, experience, contact } = req.body;
//
//    const prompt = `
//    Generate a professional resume in HTML format.
//    The resume should include sections for Contact Information, Summary, Skills, Experience, Projects, and Education.
//    Ensure the HTML is well-structured and uses semantic tags.
//    Include some basic inline CSS or a <style> block for a clean, readable layout.
//
//    Here is the candidate's information:
//    Contact Information: ${contact.name}, ${contact.email}, ${contact.phone}, ${contact.linkedin}
//    Skills: ${skills.join(', ')}
//    Experience: ${experience.map(exp => `${exp.title} at ${exp.company} (${exp.duration}): ${exp.details}`).join('\n')}
//    Projects: ${projects.map(proj => `${proj.name}: ${proj.description} (Tech Stack: ${proj.techStack})`).join('\n')}
//    Education: ${education.map(edu => `${edu.degree} from ${edu.institution} (${edu.year})`).join('\n')}
//
//    Output only the HTML code. Do not include any introductory or concluding text outside the HTML tags.
//    `;
//
//    try {
//        const result = await geminiModel.generateContent(prompt);
//        const response = await result.response;
//        let resumeHtml = response.text();
//
//        // Basic cleaning to remove markdown code blocks if Gemini returns them
//        if (resumeHtml.startsWith('```html')) {
//            resumeHtml = resumeHtml.substring(7, resumeHtml.lastIndexOf('```')).trim();
//        }
//
//        res.status(200).json({ html: resumeHtml });
//    } catch (error) {
//        console.error('Error generating resume HTML from Gemini:', error);
//        res.status(500).json({ error: 'Failed to generate resume HTML.' });
//    }
//});
//
//
//
// //Route to convert HTML to PDF
//app.post('/convert-to-pdf', (req, res) => {
//    const { htmlContent } = req.body;
//
//    const options = {
//        format: 'A4',
//        orientation: 'portrait',
//        border: '10mm',
//        header: {
//            height: '10mm',
//            contents: '<div style="text-align: center; font-size: 10px;">Generated by AI Resume Builder</div>'
//        },
//        footer: {
//            height: '10mm',
//            contents: '<span style="color: #444; font-size: 10px;">{{page}}</span>/<span>{{pages}}</span>'
//        }
//    };
//
//    pdf.create(htmlContent, options).toBuffer((err, buffer) => {
//        if (err) {
//            console.error('Error converting HTML to PDF:', err);
//            return res.status(500).json({ error: 'Failed to convert HTML to PDF.' });
//        }
//        res.setHeader('Content-Type', 'application/pdf');
//        res.send(buffer);
//    });
//});



